const { Router } = require('express')
const router = Router()
const controller = require('./controller')
router.get('/', controller.home)
router.get('/create', controller.createPage)
router.get('/auth', controller.authPage)
router.get('/signin', controller.signinPage)
router.get('/files', controller.filesPage)
router.post('/create', controller.createTodo)
router.post('/complete', controller.completeTodo)
router.post('/delete', controller.deleteTodo)
router.post('/auth', controller.authUser)
router.post('/signin', controller.signinUser)
router.post('/upload', controller.fileUpload)
router.get('/signout', controller.signoutUser)
module.exports = router